[project]
name = "wangtrader"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Alec Wu", email = "wuiw.tw@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["tests"]
testpaths = ["tests"]
